### ISSUE TITLE
[ not cacheable ] [ built ]

### ISSUE THREAD

**Issue by WilliamHolmes** [jballant/webpack-strip-block#1]
More than likely not a bug or my own doing but I thought I would mention the following.
...
loaders: ['webpack-strip-block', 'react-hot', 'babel', 'eslint']
...
When I build I see this printed in the console ...

./src/js/components/App.js 3.57 kB {0} **[not cacheable]** [built]

not sure why it would print [ not cacheable ], and this is only shown when I used the webpack-strip-block loader.

**Comment by jballant** [comment]
Thanks for letting me know.

It's definitely not your fault. That warning message about loaders not being cacheable did not occur when I wrote this, but there is no reason why the result should be cacheable. 

I could not reproduce the issue locally, however, I updated the master branch to use the "cacheable" method in the loader, which I hope will fix the problem. I am going to try and test it some more before I tag and publish to npm.
