### ISSUE TITLE
Update for Webpack 4

### ISSUE THREAD

**Issue by ghost** [jballant/webpack-strip-block#11]
Can you update?

**Comment by jballant** [comment]
I've tested this plugin locally with webpack `4.1.1` and it was still working for me. Is there a particular scenario that isn't working for you?

**Comment by ghost** [comment]
It did not remove. My way might be wrong. I found another plugin that author updated and i am using it now. Thanks.

**Comment by jballant** [comment]
OK. Glad you found something that worked for you. If you ever are so inclined, feel free to post more information about how you had had your webpack/source code set up with this loader--I might be able to identify the problem.
