### ISSUE TITLE
Webpack 2 issue: A valid query string passed to parseQuery should begin with '?'

### ISSUE THREAD

**Issue by wbern** [jballant/webpack-strip-block#4]
```
ERROR in ./src/main/js/main.js
Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
    at Object.parseQuery (/home/wbern/IdeaProjects/gakusei/node_modules/loader-utils/lib/parseQuery.js:13:9)
    at Object.StripBlockLoader (/home/wbern/IdeaProjects/gakusei/node_modules/webpack-strip-block/index.js:11:29)
 @ multi ./src/main/js/main.js
```

Can be resolved by changing 

```
var query = loaderUtils.parseQuery(this.query);
```

to

```
var query = (this.query === '' ? {} : loaderUtils.parseQuery(this.query));
```

More on the issue (and changes) can be found in this webpack issue. https://github.com/webpack/loader-utils/issues/56

Basically you can't pass empty queries anymore

A simpler work-around for users finding this, without changing the code, would be to add some options like below.

```
rules: [
      {
        test: /\.jsx?$/,
        enforce: 'pre',
        exclude: /(node_modules|bower_components|\.spec\.js)/,
        use: [
          'webpack-strip-block?start=devcode:start&end=devcode:end'
        ]
      }
    ]
```

Also as a side-note, the config in the README.MD is not webpack 2.x compatible, as can be seen from the syntax in above work-around.

**Comment by jballant** [comment]
You are quite correct that the plugin needs to be updated for Webpack 2. Thanks for letting me know.

I will try and publish an update when I can.

**Comment by wbern** [comment]
@jballant PR created.

**Comment by jballant** [comment]
PR merged and new version published.
