### ISSUE TITLE
No support for object syntax in Webpack 2

### ISSUE THREAD

**Issue by rasmusnord** [jballant/webpack-strip-block#6]
This loader supports the old query format from Webpack 1, but not the new object syntax in Webpack 2.

Supporting both can be accomplished by using [loaderUtils.getOptions](https://github.com/webpack/loader-utils#getoptions).

**Unsupported configuration case:**

```
{
  loader: "webpack-strip-block",
  options: {
    start: "DEBUG_START",
    end: "DEBUG_END"
  }
}
```

**Comment by jballant** [comment]
Thanks for the PR. I like the idea of supporting different comment syntaxes for different file types, though I'm not sure it's necessary to also support multiple block declarations. You could just add rules for each block you want to strip.

Maybe something like this? It would not be a breaking change:
```javascript
options: {
      start: 'DEV-START',
      end: 'DEV-END'
      commentStart: '/*', // defaults to '/*'
      commentEnd: '*/' // defaults to '*/'
}
```
Also, I can't merge this with the url for the repo being changed. I assume you are publishing your fork, so folks can use that while I mull over how to proceed.
